"use client";
import Navbar from "@/components/NavBar/Navbar";
import "./globals.css";
import { usePathname } from "next/navigation";
import { UserProvider } from "@/context/UserContext";

// export const metadata = {
//   title: "EvHomes",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body
        className="container"
        style={{ paddingTop: pathname === "/" ? 0 : 60 }}
      >
        <UserProvider>
          <Navbar />
          {children}
        </UserProvider>

        {/* {children} */}
      </body>
    </html>
  );
}
